### ISSUE TITLE
regression: error saving new streets

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#422]
after merging https://github.com/3DStreet/3dstreet/pull/395

attempting to save a street imported from streetmix results in error:
> Error trying to save 3DStreet scene to cloud. Error: TypeError: Cannot read properties of undefined (reading 'default')

This is my mistake, I should have done more testing before deploying this, @Algorush can you help diagnose?

Flow to reproduce:
- import new street from streetmix, like 3dstreet.app/#https://streetmix.net/kfarr/3/
- login and click remix
- note error
- there is the same error if you go to capture (camera) > export as json

To reproduce locally in this repo:
- `npm run start` go to localhost:7001/#https://streetmix.net/kfarr/3/
- in console write:
```
const entity = document.getElementById('street-container');
const data = convertDOMElToObject(entity);
```

- You can also add additional console logging from line 320:
```
for (const key in data) {
    console.log('defaultData', defaultData);
    console.log('key', key);
```

Doing so shows that the error is raised after defaultData that contains properties 'cast' and 'receive' and specifically when the key 'receive' is used with property 'default'. Cast and receive is related to shadow, so I'm expected this has to do with the addition of shadows to the scene.

I tried a bunch of things to make this work but none of them worked, you can see my weak attempts here:
https://github.com/3DStreet/3dstreet/pull/425/files

**Comment by kfarr** [comment]
Here is a "hot fix" that works: https://github.com/3DStreet/3dstreet/commit/877f0369365d0c26d0514ed97f3740bf3f68fbc6

If default value can't be fetched reliably it assumes the value is empty string ''

Is this safe to keep as is? Or should the underlying issue be investigated?

**Comment by Algorush** [comment]
After I add `shadow` nad `anisotropy` in `mixinSkipProps` constant array, it works well. But I noticed another issue - `data-layer-name` is saved as an object and not a string. And this (possibly) causes errors when loading a saved scene

**Comment by kfarr** [comment]
@Algorush  the issue with data-layer-name was resolved https://github.com/3DStreet/3dstreet/issues/423#issue-2020104964

**Comment by Algorush** [comment]
It strange. I was debugging in the repo: creator-usability-epic-v1 and trying-to-fix-422. Yesterday the save function did not work, but today it works.
About using json-utils.js from index.js. I did this in this PR: https://github.com/3DStreet/3dstreet/pull/352

**Comment by Algorush** [comment]
I finally found the reason, I was busy with other work for the last two days too. The reason for this error with `default` was that I incorrectly specified the shadow parameter property in aframe-streetmix-parser.js, https://github.com/3DStreet/3dstreet/blob/eb2b5c20a9e18fee10d611bc17b17a098f9ae2fb/src/aframe-streetmix-parsers.js#L130. 
Instead of `receive:true` I wrote `recieve:true`. There is no such default value in schema and therefore an error appeared when receiving it. I'll make a check for the presence of properties in schema for the future

**Comment by kfarr** [comment]
@Algorush ok will you make a new PR or commit or something that reverts my change if it is no longer needed, and then has your fix instead?

**Comment by kfarr** [comment]
@Algorush `creator-usability-epic-v1` branch has already been merged. The most recent changes relevant to this ticket are all on `main` branch. So you'll want to create a new branch based on `main` and then create a PR from that branch once you've made your changes.

**Comment by Algorush** [comment]
Ok, created new PR to fix this and similar errors in the future. Same fix as you @kfarr suggested, but without try/catch:
https://github.com/3DStreet/3dstreet/pull/430
I also created a PR to correct the typo that caused this error: https://github.com/3DStreet/3dstreet/pull/429. And 1 PR so that the shadow component is not saved in JSON (because it is in the corresponding mixins): https://github.com/3DStreet/3dstreet/pull/428

**Comment by kfarr** [comment]
closed by https://github.com/3DStreet/3dstreet/pull/430
