### ISSUE TITLE
user modified materials are not saved

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#462]
as a user who chooses a different material such as brick texture on a median, those changes are not saved. instead I see a white box where the brick should be.

instead I should see the material i selected
scene: https://3dstreet.app/#/scenes/73c8e705-a8a0-41b7-974c-1e504b8ba8fa.json
wrong:
![image](https://github.com/3DStreet/3dstreet/assets/470477/5366ddf9-292b-4d4d-a9ab-efda479d6741)
expected:
![image](https://github.com/3DStreet/3dstreet/assets/470477/a43314ad-c952-4eea-9ed6-bd05ee72a45a)

**Comment by Algorush** [comment]
in the case of textures loaded in this way, the `img` element with the `src` and `id` attributes is added dynamically to the `a-assets` DOM element. When saving to JSON, only the `id` value is saved. Then after loading the JSON file, there is no `img` with this `id` in `a-assets`, so the texture is not loaded.
A possible solution here is to store the `src` attribute instead of the `id` for the material texture in case the texture is loaded this way

**Comment by Algorush** [comment]
https://github.com/3DStreet/3dstreet/pull/465

**Comment by kfarr** [comment]
closed by #465
