### ISSUE TITLE
streetplan-loader component

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#498]
As a user of [StreetPlan.net](https://streetplan.net/), I wish to export my street scene into 3DStreet for further modifications, creating visuals and sharing with others.

Deliverables
- Mar 12 - scope and architecture feedback - alex + kieran
- Apr 11 - streetplan-loader component in production - alex + kieran
- modifications for streetplan output - mike + rika
- Training for 3DStreet for mike - kieran
- testing and QA - mike + rika
- documentation - mike + kieran

Notes:
- Goal for Alex in max 15 hours to “make something work” -- ie for the default streets linked above, we want something to be there left to right
- https://upd.streetplan.net/MyState/MyOrg/MyProj/79287
- https://upd.streetplan.net/streets-3d-data/79287
- Material / color is important - for discussion - example discussion, on the streetplan json data output there is, for example `"Material": "Pavers Tan"` on line 54; how should that be mapped to textures used in 3DStreet?
- which streetmix segments to map to / from - for discussion ([list of currently supported segments / variants in 3dstreet](https://github.com/3DStreet/3dstreet/blob/main/src/segments-variants.json))

**Comment by Algorush** [comment]
So far, these are my conclusions from what I saw in StreetPlan.
- In terms of StreetPlan JSON structure, it is basically similar to the streetmix structure. I think it's time to refactor the parser to adapt it to the names of segments and options of  streetPlan too. And make two files (for streetmix and streetplan) with a correspondence map: segment name (and options): handler function name. I'm still thinking about the best way to do this.
- But streetplan has many more segment variants, as well as material options. Many of them are not that difficult to add. Can we ask @gnansai to add new models? And we also will have to find/make new materials and textures similar to those in StreetPlan, I can do this. It's probably worth asking the StreetPlan developers for the most used options for each segment type in order to implement them first.
- One of the differences from Streetmix is that StreetPlan has foreground and background options for one segment and there can also be 2 foreground/background. This will need to be taken into account in 3DStreet, that is, placing different types of options on the same segment.
- Regarding the differences in the presentation of some segments. For example Sidewalk in 3DStreet has all different types of pedestrians on the same segment. StreetPlan has many very typical pedestrians on same segment, such as a 'woman shopping' or 'older ladies walking' or 'Couple',3 people, 2 people, ... The question is, should we do the same in 3DStreet - place pedestrians only of the selected option? 
- And again. We don’t yet have many types of pedestrians, such as jogging man/woman/couple, Grandpa and todler, woman with dog, couple, older couple, etc

**Comment by kfarr** [comment]
Thanks, here is a quick analysis I did on the streetplan Type values I encountered in this file: https://upd.streetplan.net/streets-3d-data/79291 as well as a manual review of the materials available in the streetplan.net user interface.

in 3dstreet, most things map to these streetmix json segment types:
- sidewalk
- drive lane (bus lane, bike lane, BRT, scooter lane, etc.)
- parking
- curb / gutter / drainage (new)
- divider

in streetplan:
- types include: Walkways, setback, Furniture, BikesPaths, Curbside, Gutter, Transit, Cars, Buffers, Buildings

Therefore, a potential mapping from 3dstreet :: streetplan could be the following:
- sidewalk :: Walkways, Furniture, Curbside
- drive-lane :: BikesPaths, Transit, Cars
- ignore :: setback, Buildings
- drainage :: Gutter
- divider :: Buffers

Streetplan material :: 3dstreet material mapping suggestion:
- many asphalt + color :: these can map to seamless road texture + color
- grass + dead grass + edging grass :: map to grass
- sidewalk - many variants :: map to sidewalk for now
- custom matierals -- pavers, sidewalk 1-9, etc.

**Comment by Algorush** [comment]
First version: https://github.com/3DStreet/3dstreet/pull/503

**Comment by Algorush** [comment]
There are several issues to discuss.
How to present some options from Streetplan in 3DStreet:
1. Sideways. Streetplan has empty, 1 man, 2 man, 3 man options, ... In Streetmix/3DStreet - empty, sparse, normal, dense variants. The number of pedestrians depends on the width of the segment, and can be from 0 to 7 and much more. 
2. Same question for cars and bikes. How much it should be. And also maybe for segments with trees, add more trees than are currently available in 3DStreet?
3. type: [Subtype, Buffers], subtype 'Purpendicular' - is this a typo? For type 'Parking' there is sybtype 'Perpendicular'
4. Currently, the Steetplan server cors settings do not allow loading JSON street project data.
5. How to form a street name for 3DStreet. Streetplan contains the name of the project, the name of the current street and the name (in the description field?) of an alternative street option.

**Comment by kfarr** [comment]
v1 done
