### ISSUE TITLE
add fly ability in viewer mode

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#600]

**Comment by vincentfretin** [comment]
movement-controls="fly:true"

Oh I see you're still using wasd-controls actually on camera rig, that's probably why I see weird rotation of camera in viewer mode, because look-controls is on the rig and not the camera. wasd-controls and look-controls are meant to be on the camera, not the rig, but then it conflicts with cursor-teleport that moves the rig and not the camera. That's why you need to switch to movement-controls on rig and look-controls on camera, and remove wasd-controls usage.

**Comment by kfarr** [comment]
@vincentfretin i was trying to have one camera rig (aka "Viewer") that is used in all cases for vr, mobile ar, desktop which motivated this structure for having a camera rig instead of something simpler. for in vr teleport and cursor teleport a rig was needed.

discussion on similar topics from 2019:
https://github.com/aframevr/aframe/pull/3394#issuecomment-483590639

> That's why you need to switch to movement-controls on rig and look-controls on camera, and remove wasd-controls usage.

So the plan would be:
- put look-controls on camera instead of rig
- use movement-controls on rig (this repo https://github.com/c-frame/aframe-extras/tree/master/src/controls) instead of wasd-controls on rig

**Comment by kfarr** [comment]
ok here's a PR for this. it seems to work exactly the same, including that the fly option does not work.
https://github.com/3DStreet/3dstreet/pull/749

**Comment by vincentfretin** [comment]
I fixed the issue in your PR.
