### ISSUE TITLE
ability to have image previews for models

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#632]
* related to #576 and previous work from @vincentfretin and myself on a model json format
* what is the best way to provide for image previews for models on the add layer panel?

**Comment by Algorush** [comment]
We can try to generate model images automatically. Write a function that will take images of all models. If all models are already loaded into page memory, then this should not take up many resources?? But I'm not sure if this is a good idea. 
Maybe It might be better to have such a generator as a separate script, which will create images of models and place them in a separate folder. The downside here is that we will have to load all images of models onto the page from the server

**Comment by kfarr** [comment]
@Algorush was already have a script that can generate jpegs from gltf, see https://github.com/3DStreet/citybuilderjr

this task is the ability for the add entity panel to reference some sort of json like catalog.json for the image file. How we create the image file is a task for another ticket (or to be done manually)

**Comment by Algorush** [comment]
> this task is the ability for the add entity panel to reference some sort of json like catalog.json for the image file.

Ok, got it.
Now there is a file `cardsData.js`, where img, icon, name for each mixinId can be stored. It is better to rename it to `mixinsData.js`, because there will be only mixins data now. Use this data in the `getGroupedMixinOptions` function in `addLayerPanel`: https://github.com/3DStreet/3dstreet/blob/95b81ab695050f92be0884dd48ecfb0d862a4d0b/src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx#L52-L58
We can also remove the grouping logic from this function and instead divide the mixins into groups inside mixinsData.js. Like in src/assets.js.

**Comment by kfarr** [comment]
@Algorush I tried adding an image to `Bicycle_1` mixin in this branch: https://github.com/3DStreet/3dstreet/pull/683 but I was not able to make it work. Can you check it out and suggest what I might be doing wrong?

**Comment by Algorush** [comment]
> @Algorush I tried adding an image to `Bicycle_1` mixin in this branch: #683 but I was not able to make it work. Can you check it out and suggest what I might be doing wrong?

also need to import `mixinsData` from `cardsData.js` file in `AddLayerPanel.component.js` and add `img: mixinsData[mixinId]` here:
https://github.com/3DStreet/3dstreet/blob/95b81ab695050f92be0884dd48ecfb0d862a4d0b/src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx#L52-L58
same for description

**Comment by kfarr** [comment]
@Algorush since this is not implemented yet per se, instead of using cardsData.js I'd like to use the catalog.json file. I have uploaded this in the PR here: https://github.com/3DStreet/3dstreet/pull/683

Please add support in the AddLayerPanel.component.jsx file to reference catalog.json and use the id, img, name and description fields (if existing) to match with mixins in the add layer panel to provide preview image, display name, and description.

**Comment by Algorush** [comment]
> @Algorush since this is not implemented yet per se, instead of using cardsData.js I'd like to use the catalog.json file. I have uploaded this in the PR here: #683
> 
> Please add support in the AddLayerPanel.component.jsx file to reference catalog.json and use the id, img, name and description fields (if existing) to match with mixins in the add layer panel to provide preview image, display name, and description.

Maybe it should also be divided into the same groups inside catalog.json, as in assets.js? Then there will be no need to divide into groups inside addLayerPanel.component.js. The downside is that we will need to divide into groups in two places - in assets.js and catalog.json

**Comment by vincentfretin** [comment]
From my discussion with @kfarr, the long term idea is to later introduce a `category` key in catalog.json. And in `addLayerPanel` component, read from `catalog.json` directly instead of `document.querySelectorAll('a-mixin')` and just using a useMemo to filter the items for the selected category. And also rewrite `assets.js` to create the mixins from `catalog.json`.

But first we'll simply read the `catalog.json` to get the additional metadata img, name and description.

**Comment by Algorush** [comment]
Thanks for let me know. So the next step is this? https://github.com/3DStreet/3dstreet/issues/678

**Comment by kfarr** [comment]
https://github.com/3DStreet/3dstreet/pull/683 yes

looks like that's ready for review?

**Comment by Algorush** [comment]
> #683 yes
> 
> looks like that's ready for review?

Yes, I mention that have done it. Here: 

> So far I've done it with what I have.

**Comment by kfarr** [comment]
done enough
