### ISSUE TITLE
when using transform controls and releasing the click, sometimes another object is selected

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#645]
might be caused near here:
https://github.com/3DStreet/3dstreet/blob/main/src/editor/lib/raycaster.js#L75
```
  function handleClick(evt) {
    // Check to make sure not dragging.
    const DRAG_THRESHOLD = 0.03;
    if (onDownPosition.distanceTo(onUpPosition) >= DRAG_THRESHOLD) {
      return;
    }
    inspector.selectEntity(evt.detail.intersectedEl);
  }
```

**Comment by kfarr** [comment]
it was hard for me to find a way to reproduce this but i finally got a video of it:

https://github.com/user-attachments/assets/fbc49855-1066-498a-bf51-f14bb058e63c

**Comment by vincentfretin** [comment]
Oh yes indeed, if the selection box is smaller than the square of the TransformControls so that click can happen on another entity and distance traveled is less than 0.03, we have the issue.

We also have the issue with EditorControls, just dragging less than 0.03 will select the entity under the cursor.

A good fix would be to get the events from TransformControls and EditorControls, and if we had any, ignore selecting the entity in raycaster handleClick, instead of relying on a 0.03 drag threshold.
