### ISSUE TITLE
preview entity shows up when loading new scene sometimes

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#747]
sometimes the preview entity will show up with a seemingly random mixin when opening a new scene from open modal

also doesn't go away when pressing "new" this case

here is a video:
https://github.com/user-attachments/assets/b074fa05-7ca4-4f3e-b7bd-90135b01955e

**Comment by kfarr** [comment]
is it possible that there is a collision between div id between add entity panel card mouseenter/leave and open modal card mouseenter/leave?

for example the addentity card div using "id"
https://github.com/3DStreet/3dstreet/blob/main/src/editor/components/components/AddLayerPanel/AddLayerPanel.component.jsx#L434-L438

and here is the open modal card div which uses "key" instead of id
https://github.com/3DStreet/3dstreet/blob/main/src/editor/components/components/SceneCard/SceneCard.component.jsx#L140-L151

i note they share the same classname

**Comment by vincentfretin** [comment]
No that's not related to mouseenter/mouseleave. It's the street component that put back previewEntity visible to true here when toggling vehicles.
https://github.com/3DStreet/3dstreet/blob/c135fe626a96ff61a8e20c8e6c6df6db7bcb4755/src/index.js#L40-L46
`streetUtils.getVehicleEntities()` is getting all entities from the scene, not just 3dstreet-container.
https://github.com/3DStreet/3dstreet/blob/c135fe626a96ff61a8e20c8e6c6df6db7bcb4755/src/street-utils.js#L83-L113

Instead of toggling visibility of previewEntity, better just remove it and recreate it as needed. This should ix #737 as well.

**Comment by vincentfretin** [comment]
Fixed in #748
