### ISSUE TITLE
regression: loading street from drag-n-drop or open panel results in incorrect lights

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#837]
on main, not deployed:

when loading a streetmix street via URL hash: http://localhost:3333/#https://streetmix.net/kfarr/3/example-street it loads as expected with proper lights and shadow [1]

when loading from the open > load streetmix modal the shadow is incorrect and the lights do not appear as children under environment [2]

also after clicking new scene, then drag and dropping a preset street, the placed street has incorrect lighting and there are no lights as expected under environment panel [3]

images

[1]
![Image](https://github.com/user-attachments/assets/5f9efb3e-e5cd-4197-b92a-a9416bd402aa)

[2]
![Image](https://github.com/user-attachments/assets/7a39b31e-6a67-4285-a4ce-c6564bf8b418)

[3]

![Image](https://github.com/user-attachments/assets/2edf422b-2a75-4cc4-9cad-1e3b4a9a1167)

**Comment by kfarr** [comment]
Investigating but I think this may be related to changes we made together @vincentfretin , anything quick come to mind? Something related to new scene changes?

**Comment by kfarr** [comment]
Ok I found a fix but it seems like a hack. What do you think? https://github.com/3DStreet/3dstreet/pull/839

**Comment by vincentfretin** [comment]
Your hack didn't fix the issue for me, and it should be 'preset: day', not 'day' btw.
The issue is that the checkOrCreateEntity removes the children, so the lights of the environment entity, and the street-environment component is not aware of it. The proper fix is to remove the component first, do the checkOrCreateEntity although it's probably not needed, and then add back the component.

**Comment by vincentfretin** [comment]
I updated your PR with a proper fix of the issue. A component that creates children should be responsible of removing them, and not some other external function.
