### ISSUE TITLE
regression: cannot double click to move camera

### ISSUE THREAD

**Issue by kfarr** [3DStreet/3dstreet#843]
on main, via localhost, (not deployed no production yet) if I load a scene that has geospatial, or I create a new scene from scratch that uses geospatial google 3d maps, when I double click on an entity in the viewport or in the scene graph panel the camera does not move to the object as expected.

If I import a streetmix scene such as the URL path as follows, the double click to move DOES work:
http://localhost:3333/#https://streetmix.net/kfarr/3/example-street

However if I add a 3d tiles geo to that, then double click to focus stops working

**Comment by kfarr** [comment]
(cannot reliably reproduce)

**Comment by kfarr** [comment]
example of error video
https://github.com/user-attachments/assets/0132b838-5d07-47ef-9b09-14613b8bcb2f
3dstreet scene json
[data - 2024-09-08T184353.506.json.zip](https://github.com/user-attachments/files/16933758/data.-.2024-09-08T184353.506.json.zip)

**Comment by kfarr** [comment]
@vincentfretin could use your help debugging this. I wonder if it's related to upgrading to a-frame 1.6 and the "fake component" thing that is somehow affected when adding google map?

**Comment by vincentfretin** [comment]
I think I saw that warning way before we implement the animation and upgrade aframe. I don't see it now.
I just tested your json, I indeed reproduce the issue, the double click doesn't work at all for this scene, but I don't see the warning so that's probably a different issue. On another scene like the default streetmix scene, double click works. It will be a fun one to debug for sure :D

**Comment by vincentfretin** [comment]
Ah indeed, just adding google tiles and the double click stops working.

**Comment by kfarr** [comment]
@vincentfretin reverting to a-frame 1.5 fixes the issue

**Comment by vincentfretin** [comment]
Yes revert to 1.5 or keep master and disable the animation code. So the bug is in the animation code it seems.

**Comment by kfarr** [comment]
@vincentfretin yes although I wonder if it's the fake component thing, would it be worth making a real component? that disables pausing similar to 3dtiles, etc. components?

**Comment by kfarr** [comment]
closed by #850

**Comment by vincentfretin** [comment]
Yeah maybe, not sure how it's related.
Reverting the animation thing make the double click on viewport work again but double clicking from the scene graph still doesn't work.
That's really a strange bug for sure, I'll be looking at the code of all the geo components as well to see if there is anything that ring a bell.

**Comment by vincentfretin** [comment]
Tested with aframe 1.5.0, there were two issues with double click on item in scene graph, fixed in #855

**Comment by vincentfretin** [comment]
> @vincentfretin yes although I wonder if it's the fake component thing, would it be worth making a real component? that disables pausing similar to 3dtiles, etc. components?

on aframe master, the geo component somewhat pause my fake component, the tick function is not executed anymore, so yeah probably making it a real component on an entity would be better.

**Comment by vincentfretin** [comment]
more precisely, it's loading the script 
```js
loadScript(
        new URL(
          '/src/lib/aframe-loader-3dtiles-component.min.js',
          import.meta.url
        ),
        () => {}
      );
```

that triggers pausing the fake component.

Actually it's just registering dynamically a new component that probably remove my tick function from executing because it's not from a real component I guess, you can reproduce in the console
`AFRAME.registerComponent('loader-3dtiles', {})`
so yeah you're right, doing the real thing will fix the issue.
