### ISSUE TITLE
Question: How does assets.js work?

### ISSUE THREAD

**Issue by mi-skam** [3DStreet/3dstreet#98]
Hi there,

I'd like to understand how the streetmix-assets component in [src/assets.js](https://github.com/3DStreet/3dstreet/blame/main/src/assets.js#L154) does its job, but struggle to understand why it's so "complicated".  Here are my questions:

1. Why is AFRAME not in the namespace at runtime and hence `window.AFRAME` needed?
2. I couldn't find a reference to the prototype property of the `streetmix-assets` definition. Does it mean it modifies the `createdCallback` and `attachedCallback` methods it inherited ? And what's the reason for that?
3. Where did you find out about `AFRAME.ANode.prototype` ?
4. Did you basically re-created a-assets-item ?

Thanks in advance!
Maksim

**Comment by kfarr** [comment]
Hi Maksim, sorry for delay, I was out on holiday.

The primary value is that the assets can be modified at runtime by the application that is using 3dstreet. The only use at the moment is the ability to set a path for the assets that can vary depending on environment (ie fetch assets locally when doing local dev, fetch assets from a specific CDN, etc.) Future use will leverage the ability to change asset packs or selectively load only specific assets required for a given scene.

As for the logic of assets.js, I would actually ask @zach-capalbo to comment on that if he's available. This was adapted from his work on a similar implementation for Vartiste. Here are docs from that project: https://vartiste.xyz/docs.html#Assets

**Comment by zach-capalbo** [comment]
Hi Maksim,

The reason for the complexity is that street view needs to dynamically inject it's assets into the scene. This becomes tricky because `a-assets` gets created in the document body, after the streetmix javascript has been included in the header. This is a scheme to try to intercept the creation of `a-assets` and get them to wait for streetmix assets just like assets defined in the document body. It's not perfect, but seems to work. There is a stack overflow question / answer that goes into a little more detail here: https://stackoverflow.com/questions/64841550/a-frame-scene-initializes-before-assets-ready-when-dynamically-adding-a-asset-i/64868581#64868581

To answer your questions:

1. I don't know that there's actually a good reason.
2. The `streetmix-assets` prototype is here: https://github.com/3DStreet/3dstreet/blame/main/src/assets.js#L155 It inherits from the `a-node` prototype, and overrides the `createdCallback` and `attachedCallback` in order to 1) pose as an `a-asset-item` so `a-assets` will wait for it to load, and 2) implement similar functionality to `a-assets` so that it can load children elements
3. The a-frame source code: https://github.com/aframevr/aframe/blob/v1.2.0/src/core/a-node.js
4. Yes, but more of a mix of `a-asset-item` and `a-assets` that allows nested asset trees

**Comment by kfarr** [comment]
Thanks @zach-capalbo for the follow-up! I have added some of this info to the [main readme](https://github.com/3DStreet/3dstreet#automatic-asset-loading) and [developer documentation](https://github.com/3DStreet/3dstreet/blob/main/src/README.md#assetsjs). I will mark this issue as closed now and can re-open if any additional info is needed.
